# Generated by Django 5.1.6 on 2025-06-21 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='seat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='empty', max_length=10)),
                ('seatid', models.CharField(max_length=10)),
            ],
        ),
    ]
